name: regressly
description: Aplicación de analítica predictiva offline para productores lecheros

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.0
  fl_chart: ^0.68.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/icon_vaca.png
    - assets/images/icon_regressly.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon_regressly.png"
  adaptive_icon_background: "#2E7D32"  # Color verde fondo
  adaptive_icon_foreground: "assets/images/icon_regressly.png"
  min_sdk_android: 21